class ColumnViewerConfig {
  // configuration for the column based synoptic witness viewer.
  // If you change something here, it might make other changes necessary.
  // Eg. you probably would have to rewrite some of the css.

  // this is the path to the file containing the paths and metadata html snippets
  // generated by the generetate_snippets.xsl script
  snippetLogPath = "./witness_snippets/snippet_paths.json";

  // the id of the top level container for the witness columns
  witnessContainerId = "witness-container";
  columnAdderId = "column-adder";
  scrollTogglerId = "scroll-toggler";
  emptyLineTogglerId = "empty-line-toggler";
  globalLinenrTogglerId = "global-linenr-toggler";
  localLinenrTogglerId = "local-linenr-toggler";
  defaultColumnNumber = 3;
  GLOBAL_SCROLL_CLASS = "global-scroll-vertical";
  INDIVIDUAL_SCROLL_CLASS = "individual-scroll-vertical";
  witness_line_class = "witness-line";
  omitted_line_class = "om";
  hidden_element_class = "hidden";
  global_line_counter_class = "linenr-global";
  local_line_counter_class = "linenr_own";
  highlight_class = "highlight";
  neigh_class = "neigh";
  text_content_class = "text-content";
  witness_class = "witness";
  controls_container_class = "controls-container";
  dropdown_class = "witness-dropdown";
  remove_column_button_class = "remove-column-button";
  dropdown_class = "text-select";
}

export default ColumnViewerConfig;